<div class="contenido-informacionTarea">
<div class="div-verTarea">
    <div>
    <p class="titulo">Título:</p>
    <p class="informacion">Análisis de succesiones y series de números reales</p>
    </div>

    <div>
    <p class="titulo">Estudiante:</p>
    <p class="informacion">Sergi Puig Biosca</p>
    </div>

    <div>
    <p class="titulo">Fecha de apertura:</p>
    <p class="informacion">10/04/2025</p>
    </div>

    <div>
    <p class="titulo">Fecha de entrega:</p>
    <p class="informacion">30/04/2025</p>
    </div>

    <div>
    <p class="titulo">Calificación:</p>
    <p class="informacion">-</p>
    </div>

    <div class="descripcion-tarea">
    <p class="titulo">Descripción de la tarea:</p>
    <textarea name="descripcion" id="descripcionTarea" class="informacion"></textarea>
    </div>

<div class="adjunto-archivos-linea">
    <label class="form-label titulo" for="taskFile">Adjuntar archivos:</label>
    <div class="file-input-wrapper">
        <input type="file" class="file-input" id="taskFile" />
        <button type="button" class="file-input-button informacion" onclick="document.getElementById('taskFile').click();">
            <span>Subir archivo</span>
        </button>
    </div>
</div>

</div>
</div>
<button class="boton-revisar boton-centro">ENTREGAR</button>