<footer style="background-color: #0D273D; color: white; padding: 10px; max-height: 98px; text-align: center;">
    <div style="
        display: flex;
        justify-content: space-evenly;
        flex-wrap: wrap;
        max-width: 1200px;
        margin: 0 auto;
        text-align: center;
    ">
        <div style="flex: 1; max-width: 300px; min-width: 250px; padding: 1rem;">
            <!-- Columna 1 -->
            <p>Contactanos: edusync@gti.com</p>
        </div>
        <div style="flex: 1; max-width: 300px; min-width: 250px; padding: 1rem;">
            <!-- Columna 2 -->
            <p>© 2025 - EduSync | Matriz de GTI</p>
        </div>
        <div style="flex: 1; max-width: 300px; min-width: 250px; padding: 1rem;">
            <!-- Columna 3 -->
            <img src="../../../imagenes/GTIBlancosdsds.png" style="max-height: 50px; margin-top: -20px; margin-bottom: -20px;">
        </div>
    </div>
</footer>
