<header>
        <a href="./">
            <img src="../../../imagenes/LogoEduSyncAzul.png" alt="Logotipo">
        </a>
    
        <nav>
            <ul>
                <input type="button" value="CONTACTO" onclick="location.href='./src/app/EduSync/contacto.php'">
                <!-- login-->
                <input type="button" value="LOGIN" onclick="location.href='./src/app/EduSync/login.php'">
            </ul>
        </nav>
</header>