        <div class="contenedor-tareasProfesor">
            <!--Aquí empiezan los filtros-->
        <div class="contenedor-botones">
            <button class="boton-revisar-profesor">Elimnar Tarea</button>
            <button class="boton-revisar-profesor">
                <img class="imgMas"src="../../../../images/pluspurple.png" alt="">
                Nueva Tarea
            </button>
        </div>
        <!--Aquí terminan los filtros-->
        <table>
            <!--Aquí empieza el encabezado de la tabla-->
            <thead class="encabezado-tabla-tareasProfesor">
                <tr class="fila-tabla-profesorTareas"> <!--Esto es una fila de la tabla-->
                    <th class="nombre-tarea-encabezado-vProfesor">Nombre Tarea</th>
                    <th class="fecha-apertura-vProfesor">Fecha de apertura</th>
                    <th class="fecha-entrega-vProfesor">Fecha de entrega</th>
                    <th class="acciones-vProfesor">Acciones</th>
                </tr>
            </thead>
            <!--Aquí termina el encabezado de la tabla-->
            <!--Aquí empieza el contenido-->
            <tbody>
                <tr class="fila">
                    <td class="nombre-tarea-vProfesor">Sprint 4</td>
                    <td class="fecha-apertura-vProfesor">20/05/2025</td>
                    <td class="fecha-entrega-vProfesor">30/05/2025</td>
                    <td class="acciones"><button class="boton-revisar-profesor">Editar</button>
                    <button class="boton-revisar-profesor">Ver Entregas</button></td>

                </tr>

                <tr class="fila">
                    <td class="nombre-tarea-vProfesor">Sprint 3</td>
                    <td class="fecha-apertura-vProfesor">30/04/2025</td>
                    <td class="fecha-entrega-vProfesor">17/05/2025</td>
                    <td class="acciones"><button class="boton-revisar-profesor">Editar</button>
                    <button class="boton-revisar-profesor">Ver Entregas</button></td>
                </tr>

                <tr class="fila">
                    <td class="nombre-tarea-vProfesor">Sprint 2</td>
                    <td class="fecha-apertura-vProfesor">10/04/2025</td>
                    <td class="fecha-entrega-vProfesor">27/04/2025</td>
                    <td class="acciones"><button class="boton-revisar-profesor">Editar</button>
                    <button class="boton-revisar-profesor">Ver Entregas</button></td>
                </tr>
            </tbody>
        </table>
        </div>